/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidcpp_HelloWorldJNI */

#ifndef _Included_com_example_androidcpp_HelloWorldJNI
#define _Included_com_example_androidcpp_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidcpp_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_androidcpp_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidcpp_HelloWorldJNI
 * Method:    returnInteger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidcpp_HelloWorldJNI_returnInteger
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidcpp_HelloWorldJNI
 * Method:    returnIntegerSwift
 * Signature: ()Ljava/lang/String;
 */
//JNIEXPORT jint JNICALL Java_com_example_androidcpp_HelloWorldJNI_returnIntegerSwift
  //      (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
